app: rag-pipelines
partOf: rag-base

argocdNamespace: openshift-gitops

vcs:
  uri: https://github.com/davidseve/rag-utils.git
  ref: main
  name: alpha-hack-program/rag-utils
  dir: pipelines

gitSslVerify: true

# gitPatSecretName: git-pat-tk-secret
pipelinesServiceAccountName: build-bot-sa

dataScienceProjectDisplayName: rag-base
dataScienceProjectNamespace: rag-base

createNamespace: true

kfpUpsertTektonPipelineName: kfp-upsert-pl

pipelinesWorkspaceDefaultSize: 2Gi

pythonImage:
  version: "3.9"
  name: "python"
  tag: "3.9-ubi8"

mountCaCerts: "false"

setup:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

workingDir: /opt/app-root/src/data

embeddingsDefaultModel: multilingual-e5-large-gpu

embeddings:
  - name: multilingual-e5-large-gpu
    url: http://multilingual-e5-large-gpu-predictor:8080
    model: multilingual-e5-large-gpu
    api_key: ""
